# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf4bc9f0a301ca37ae951a318e027f49f951026c70c91ede119c7cd82b23cd54642bea8f4b0248cd62dae9442766c3ad343ad3a5bd7554e65f1145cfd4f266d

test:
  secret_key_base: bd89f0c1dd64aa2de3844a59c9d55c389970e5b533eeb7ec1a7b3dab284b0fd23821cd8cc4fdfc4a64d95f7309250f2b7352c77c7b6ef91823cf698dd53a4562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
